[env:genericSTM32F401RC]
platform  = ststm32
board     = genericSTM32F401RC
framework = stm32cube

extra_scripts = pre:scripts/usb_middleware.py

build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F401xC
    -DHSE_VALUE=25000000UL
    -I${PROJECT_DIR}/include

upload_protocol = dfu
monitor_speed   = 115200
